name: qdnaseq-cnv
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.2.2
  - bioconductor-qdnaseq=1.38.0
  - bioconductor-qdnaseq.hg19
  - bioconductor-qdnaseq.hg38
  - r-optparse
  - r-future
  - r-data.table
  - python=3.9
  - pandas
  - numpy
  - htslib  # for bgzip and tabix
  - samtools
  - pip
  - pip:
    - argparse