name: spectre
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - pysam=0.22.0
  - pandas=2.0.1
  - numpy=1.24.3
  - scipy=1.10.1
  - matplotlib=3.7.1
  - pip
  - pip:
    - spectre-cnv