repository_type: pipeline

nf_core_version: 3.2.0

lint: {}

template:
  org: nf-core
  name: nanoraredx
  description: A Nextflow pipeline for rare disease diagnostics from Oxford Nanopore
    long-read sequencing data. Includes SV, SNV, CNV, and methylation profiling.
  author: Nour Mahfel
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features: []
  is_nfcore: true
