contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #nanoraredx channel"
    url: https://nfcore.slack.com/channels/nanoraredx
    about: Discussion about the nf-core/nanoraredx pipeline
