name: "truvari_collapse"
description: "Collapse structural variants using Truvari to merge similar variants within a single VCF file"
keywords:
  - structural variants
  - sv
  - vcf
  - collapse
  - merge
  - truvari
tools:
  - "truvari":
      description: "Structural variant toolkit for VCF files"
      homepage: "https://github.com/ACEnglish/truvari"
      documentation: "https://github.com/acenglish/truvari/wiki"
      tool_dev_url: "https://github.com/ACEnglish/truvari"
      doi: "10.1186/s13059-022-02840-6"
      licence: ["MIT"]
      identifier: ""

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test' ]`
    - vcf:
        type: file
        description: Input SV VCF file to collapse
        pattern: "*.{vcf,vcf.gz}"
        ontologies:
          - edam: http://edamontology.org/format_3016 # VCF
    - tbi:
        type: file
        description: Input SV VCF index file
        pattern: "*.{tbi,csi}"
        ontologies: []
    - bed:
        type: file
        description: Optional BED file containing regions to restrict analysis
        pattern: "*.bed"
        ontologies:
          - edam: http://edamontology.org/format_3003 # BED
  - - refdist:
        type: integer
        description: Reference distance for merging variants (bp)
  - - pctsim:
        type: float
        description: Percent similarity threshold for merging variants (0.0-1.0)
  - - pctseq:
        type: float
        description: Percent sequence similarity threshold for merging variants (0.0-1.0)
  - - passonly:
        type: boolean
        description: Flag to only keep PASS variants in output
  - - dup_to_ins:
        type: boolean
        description: Flag to treat duplications as insertions during merging

output:
  merged_vcf:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test' ]`
      - "*_merged.vcf":
          type: file
          description: VCF file containing merged structural variants
          pattern: "*_merged.vcf"
          ontologies:
            - edam: http://edamontology.org/format_3016 # VCF
  collapsed_vcf:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test' ]`
      - "*_collapsed.vcf":
          type: file
          description: VCF file containing collapsed structural variants
          pattern: "*_collapsed.vcf"
          ontologies:
            - edam: http://edamontology.org/format_3016 # VCF
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML

authors:
  - "@nourmahfel"
maintainers:
  - "@nourmahfel"